hero.property=Hero Profile Dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:mysql://192.168.1.100:3306/hero-DB


app.testProp=cccccccc